---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Make sure NGINX is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Start Page
  template:
    src: welcome.html.j2
    dest: /var/www/html/welcome.html
- name: Set the vhost
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-enabled/welcome.conf
    mode: "0644"
  notify: Restart nginx

- name: Remove default site if present
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx
