---
name: Ansible lint 

on:
  push:
    branches: [ "main" ]

    paths:
      - '**.yml'
      - '**.yaml'
      - '**/roles/**'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  lint-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a in Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/nginx_play" \
            -w /nginx_play \
            cytopia/ansible-lint \
            bash -c "git config --global --add safe.directory /ansible_project && ansible-lint playbook.yml"
