---
name: Ansible lint

on:
  push:
    branches: [ "main" ]

    paths:
      - '**.yml'
      - '**.yaml'
      - '**/roles/**'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  lint-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a in Doceker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/data" \
            -w /data \
            cytopia/ansible-lint \
            ansible-lint playbook.yml